// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using starwars_browser_server.Models;

namespace starwarsbrowserserver.Migrations
{
    [DbContext(typeof(StarshipContext))]
    [Migration("20181217102433_InitialStarship")]
    partial class InitialStarship
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("starwars_browser_server.Models.StarshipItem", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("MGLT");

                    b.Property<string>("cargo_capacity");

                    b.Property<string>("consumables");

                    b.Property<string>("cost_in_credits");

                    b.Property<string>("crew");

                    b.Property<string[]>("films");

                    b.Property<string>("hyperdrive_rating");

                    b.Property<string>("length");

                    b.Property<string>("manufacturer");

                    b.Property<string>("max_atmosphering_speed");

                    b.Property<string>("model");

                    b.Property<string>("name");

                    b.Property<string>("passengers");

                    b.Property<string[]>("pilots");

                    b.Property<string>("starship_class");

                    b.HasKey("id");

                    b.ToTable("Starships");
                });
#pragma warning restore 612, 618
        }
    }
}
