// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using starwars_browser_server.Models;

namespace starwarsbrowserserver.Migrations.Species
{
    [DbContext(typeof(SpeciesContext))]
    [Migration("20181217104451_FetchSpecies")]
    partial class FetchSpecies
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("starwars_browser_server.Models.SpeciesItem", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("average_height");

                    b.Property<string>("average_lifespan");

                    b.Property<string>("classification");

                    b.Property<string>("designation");

                    b.Property<string>("eye_colors");

                    b.Property<string[]>("films");

                    b.Property<string>("hair_colors");

                    b.Property<string>("homeworld");

                    b.Property<string>("language");

                    b.Property<string>("name");

                    b.Property<string[]>("people");

                    b.Property<string>("skin_colors");

                    b.HasKey("id");

                    b.ToTable("Species");
                });
#pragma warning restore 612, 618
        }
    }
}
