// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using starwars_browser_server.Models;

namespace starwarsbrowserserver.Migrations.Planet
{
    [DbContext(typeof(PlanetContext))]
    [Migration("20181210182112_FetchPlanet")]
    partial class FetchPlanet
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("starwars_browser_server.Models.Planet", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("climate");

                    b.Property<string>("diameter");

                    b.Property<string[]>("films");

                    b.Property<string>("gravity");

                    b.Property<string>("name");

                    b.Property<string>("orbital_period");

                    b.Property<string>("population");

                    b.Property<string[]>("residents");

                    b.Property<string>("rotation_period");

                    b.Property<string>("surface_water");

                    b.Property<string>("terrain");

                    b.HasKey("id");

                    b.ToTable("Planets");
                });
#pragma warning restore 612, 618
        }
    }
}
